### ISSUE TITLE
dovecot-username differs

### ISSUE THREAD

**Issue by Uzilurcs** [st3fan/dovecot-xaps-plugin#7]
Thank You for implantation of Push for Dovecot.
I was very frustrated about Apples Server. 
Only a simple Update resets Settings on there App. For Example: the config of the Webserver was totally removed, and after Update, i was not able to Download Attachments from Wiki-Server.
So i switched to Linux (Rebuild OD and all other Services from Apple Server)

After a few Hours of Work, I've got it to work, an i have a small issue.
The Device register with dovecot-name "username" but when i receive an Mail, the Plugin sends the name with domain: dovecot-name username@server.int.domain.tld, so my device can't receive the Push Notification.
I edited the xapsd.json and replace the username with username@server.int.domain.tld and now it works fine.

Some logs:

35B470', 'dovecot-mailboxes': ['Sent', 'Notes', 'INBOX'], 'dovecot-username': 'uzilurcs', 'aps-subtopic': 'com.apple.mobilemail'})
2015-03-24 20:34:38+0100 [XAPSProtocol,1,] handleRegister: Command(name='REGISTER', args={'aps-account-id': '3B85D161-24B6-4A97-9AA7-4CE7CA279C6A', 'aps-device-token': 'B2C573AECD88D863E23A3CA12848D2CFEF4855080667FC94075043476D35B470', 'dovecot-mailboxes': ['Sent', 'Notes', 'INBOX'], 'dovecot-username': 'username', 'aps-subtopic': 'com.apple.mobilemail'})

2015-03-24 20:39:34+0100 [XAPSProtocol,7,] lineReceived: NOTIFY dovecot-username="username@server.int.domain.tld"    dovecot-mailbox="INBOX"
2015-03-24 20:39:34+0100 [XAPSProtocol,7,] Command(name='NOTIFY', args={'dovecot-username': 'username@server.int.domain.tld', 'dovecot-mailbox': 'INBOX'})
2015-03-24 20:39:34+0100 [XAPSProtocol,7,] handleNotify: Command(name='NOTIFY', args={'dovecot-username': 'username@server.int.domain.tld', 'dovecot-mailbox': 'INBOX'})
2015-03-24 20:39:34+0100 [XAPSProtocol,7,] APNSClientFactory.queueNotification
2015-03-24 20:39:34+0100 [XAPSProtocol,7,] APNSClientFactory.queueNotification
2015-03-24 20:39:34+0100 [XAPSProtocol,7,] APNSClientFactory.queueNotification
2015-03-24 20:39:34+0100 [XAPSProtocol,7,] APNSClientFactory.queueNotification
2015-03-24 20:39:34+0100 [XAPSProtocol,7,] APNSClientFactory.queueNotification
2015-03-24 20:39:34+0100 [XAPSProtocol,7,] APNSClientFactory.queueNotification
2015-03-24 20:39:34+0100 [XAPSProtocol,7,] APNSClientFactory.queueNotification

And another Question. I it possible to got it to work with Darwin Calendarserver on Linux?

Thanks

**Comment by m3nu** [comment]
I ran into the same issue.

**Comment by m3nu** [comment]
"Fixed" it by adding the domain during registration. Just add this line below the [username assignment](https://github.com/st3fan/dovecot-xaps-daemon/blob/master/src/cmd/xapsd/xapsd.go#L291).

`username += "@your.domain.tld"`

**Comment by freswa** [comment]
Since the backend changed, I doubt this issue still exist. If anyone is affected by this again please reopen. Thanks
